### ISSUE TITLE
Problems encountered in using the software

### ISSUE THREAD

**Issue by Only-Don** [IILab-AI/PEagent#2] opened 2024-11-15 03:14 UTC
When I open the exe program PE Agent-M, I find that the software cannot be opened and the following error window pops up, can you help me to answer this question?
![微信图片_20241115014759](https://github.com/user-attachments/assets/d4887cba-675a-4b7a-abfc-f777a6092e9d)

**Comment by sysyhh** [comment] 2024-11-18 07:54
This issue is caused by a negative value occurring when calculating the placement coordinates of components on certain special aspect ratio displays, which leads to a program execution error. This problem will be fixed in a future update.

**Closed by sysyhh** 2024-11-18 07:54 UTC

**Comment by Ackuya** [comment] 2024-12-02 04:54
<img width="694" alt="Snipaste_2024-12-02_12-49-40" src="https://github.com/user-attachments/assets/07d3b4c0-cf92-4590-96f6-3e4a8992c8ca">
I can't find the 'PE Agent-M.exe' in your files ,there only have a 'PE Agent-M.py' file and I can't open it . Can you help me to answer this question?

**Comment by sysyhh** [comment] 2024-12-02 04:54
您好，来信已收到。谢谢！

**Comment by sysyhh** [comment] 2024-12-02 05:04
You can download the exe file from the release/v1.0.0 as indicated by the arrow.
![release](https://github.com/user-attachments/assets/0c31bb57-3d9a-41e1-ab1f-5c099d5f0361)

**Comment by sysyhh** [comment] 2024-12-02 05:05
> <img alt="Snipaste_2024-12-02_12-49-40" width="694" src="https://private-user-images.githubusercontent.com/101709533/391414487-07d3b4c0-cf92-4590-96f6-3e4a8992c8ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMTU5NDksIm5iZiI6MTczMzExNTY0OSwicGF0aCI6Ii8xMDE3MDk1MzMvMzkxNDE0NDg3LTA3ZDNiNGMwLWNmOTItNDU5MC05NmY2LTNlNGE4OTkyYzhjYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMlQwNTAwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDJiNTg5MTZlNTY1MmZkMDcxMGI0OWU4NGM0NTYzYTQyMTkxYTE1ZDU1ZTQzN2ZmY2U5N2ZkOGFjNGQ0OGEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tD9BmtQPA7PwL9upRqKjo7Mrw6geCWCL10nEgTyUk8E"> I can't find the 'PE Agent-M.exe' in your files ,there only have a 'PE Agent-M.py' file and I can't open it . Can you help me to answer this question?

You can download the exe file from the release/v1.0.0 as indicated by the arrow.
![release](https://github.com/user-attachments/assets/07aa5bac-73e7-48f8-a351-be1ad9a11060)

**Comment by yyw712** [comment] 2025-12-17 13:41
<img width="461" height="214" alt="Image" src="https://github.com/user-attachments/assets/07fa7b7e-f597-43e6-b477-4f2f885234da" />我在打开PE Agent并点击微信登录之后，总是显示域名解析错误，我更改了公用DNS，用手机热点，关闭防火墙均无法解决，好像这个域名无法被解析，请问怎么解决？
